#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-gam
Version  : 1.16
Release  : 15
URL      : https://cran.r-project.org/src/contrib/gam_1.16.tar.gz
Source0  : https://cran.r-project.org/src/contrib/gam_1.16.tar.gz
Summary  : Generalized Additive Models
Group    : Development/Tools
License  : GPL-2.0
Requires: R-gam-lib
BuildRequires : R-foreach
BuildRequires : clr-R-helpers

%description
additive models, as described in chapter 7 of "Statistical Models in
		S" (Chambers and Hastie (eds), 1991), and "Generalized Additive
		Models" (Hastie and Tibshirani, 1990).

%package lib
Summary: lib components for the R-gam package.
Group: Libraries

%description lib
lib components for the R-gam package.


%prep
%setup -q -c -n gam

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532101559

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1532101559
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library gam
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library gam
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library gam
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library gam|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gam/DESCRIPTION
/usr/lib64/R/library/gam/INDEX
/usr/lib64/R/library/gam/Meta/Rd.rds
/usr/lib64/R/library/gam/Meta/data.rds
/usr/lib64/R/library/gam/Meta/features.rds
/usr/lib64/R/library/gam/Meta/hsearch.rds
/usr/lib64/R/library/gam/Meta/links.rds
/usr/lib64/R/library/gam/Meta/nsInfo.rds
/usr/lib64/R/library/gam/Meta/package.rds
/usr/lib64/R/library/gam/NAMESPACE
/usr/lib64/R/library/gam/R/gam
/usr/lib64/R/library/gam/R/gam.rdb
/usr/lib64/R/library/gam/R/gam.rdx
/usr/lib64/R/library/gam/data/gam.data.RData
/usr/lib64/R/library/gam/data/gam.newdata.RData
/usr/lib64/R/library/gam/data/kyphosis.RData
/usr/lib64/R/library/gam/help/AnIndex
/usr/lib64/R/library/gam/help/aliases.rds
/usr/lib64/R/library/gam/help/gam.rdb
/usr/lib64/R/library/gam/help/gam.rdx
/usr/lib64/R/library/gam/help/paths.rds
/usr/lib64/R/library/gam/html/00Index.html
/usr/lib64/R/library/gam/html/R.css
/usr/lib64/R/library/gam/libs/symbols.rds
/usr/lib64/R/library/gam/ratfor/backfit.r
/usr/lib64/R/library/gam/ratfor/backlo.r
/usr/lib64/R/library/gam/ratfor/linear.r
/usr/lib64/R/library/gam/ratfor/lo.r
/usr/lib64/R/library/gam/ratfor/splsm.r

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/gam/libs/gam.so
/usr/lib64/R/library/gam/libs/gam.so.avx2
/usr/lib64/R/library/gam/libs/gam.so.avx512
